config/routes.rb
Rails.application.routes.draw do
  resources :toodoo_items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/toodoo_item.rb
class ToodooItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/toodoo_items_controller.rb
class ToodooItemsController < ApplicationController
  before_action :set_toodoo_item, only: [:show, :edit, :update, :destroy]

  # GET /toodoo_items
  # GET /toodoo_items.json
  def index
    @toodoo_items = ToodooItem.all
  end

  # GET /toodoo_items/1
  # GET /toodoo_items/1.json
  def show
  end

  # GET /toodoo_items/new
  def new
    @toodoo_item = ToodooItem.new
  end

  # GET /toodoo_items/1/edit
  def edit
  end

  # POST /toodoo_items
  # POST /toodoo_items.json
  def create
    @toodoo_item = ToodooItem.new(toodoo_item_params)

    respond_to do |format|
      if @toodoo_item.save
        format.html { redirect_to @toodoo_item, notice: 'Toodoo item was successfully created.' }
        format.json { render :show, status: :created, location: @toodoo_item }
      else
        format.html { render :new }
        format.json { render json: @toodoo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toodoo_items/1
  # PATCH/PUT /toodoo_items/1.json
  def update
    respond_to do |format|
      if @toodoo_item.update(toodoo_item_params)
        format.html { redirect_to @toodoo_item, notice: 'Toodoo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @toodoo_item }
      else
        format.html { render :edit }
        format.json { render json: @toodoo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toodoo_items/1
  # DELETE /toodoo_items/1.json
  def destroy
    @toodoo_item.destroy
    respond_to do |format|
      format.html { redirect_to toodoo_items_url, notice: 'Toodoo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_toodoo_item
      @toodoo_item = ToodooItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def toodoo_item_params
      params.require(:toodoo_item).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toodoo_items_helper.rb
module ToodooItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toodoo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/toodoo_items/_form.html.erb
<%= form_with(model: toodoo_item, local: true) do |form| %>
  <% if toodoo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(toodoo_item.errors.count, "error") %> prohibited this toodoo_item from being saved:</h2>

      <ul>
      <% toodoo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/toodoo_items/edit.html.erb
<h1>Editing Toodoo Item</h1>

<%= render 'form', toodoo_item: @toodoo_item %>

<%= link_to 'Show', @toodoo_item %> |
<%= link_to 'Back', toodoo_items_path %>

app/views/toodoo_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="redColor">Toodoo Items</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @toodoo_items.each do |toodoo_item| %>
      <tr>
        <td><%= toodoo_item.description %></td>
        <td><%= link_to 'Show', toodoo_item %></td>
        <td><%= link_to 'Edit', edit_toodoo_item_path(toodoo_item) %></td>
        <td><%= link_to 'Destroy', toodoo_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Toodoo Item', new_toodoo_item_path %>

app/views/toodoo_items/new.html.erb
<h1>New Toodoo Item</h1>

<%= render 'form', toodoo_item: @toodoo_item %>

<%= link_to 'Back', toodoo_items_path %>

app/views/toodoo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @toodoo_item.description %>
</p>

<%= link_to 'Edit', edit_toodoo_item_path(@toodoo_item) %> |
<%= link_to 'Back', toodoo_items_path %>